insert into category (description) values ('German')
insert into category (description) values ('Italian')
insert into category (description) values ('Asian')
insert into category (description) values ('Fast Food')
insert into category (description) values ('Turkish')

insert into unit_of_measure (description) values ('Teaspoon')
insert into unit_of_measure (description) values ('Tablespoon')
insert into unit_of_measure (description) values ('Cup')
insert into unit_of_measure (description) values ('Ounce')
insert into unit_of_measure (description) values ('g')
insert into unit_of_measure (description) values ('ml')
